### PR TITLE
Support build image on multi arch

### PR DESCRIPTION
**Pull request by drivebyer**
https://github.com/OT-CONTAINER-KIT/redis/issues/43.

### CODE REVIEW

**Comment by shubham-cmyk** [comment]
@drivebyer 

Why push is false here

**Comment by drivebyer** [comment]
> Why push is false here?
> 
> Maybe we wanted to push the image everytime a PR is merged.

Fixed

**Review by shubham-cmyk — APPROVED** [review]
LGTM!

**Comment by shubham-cmyk** [comment]
@drivebyer Well after introducing the `qemu` the time for building the image has gone really up.  
to 2hrs previously it was 8min. 

not a big deal right now. But probably in the future, this could be a fix. Right now it works well.

**Comment by drivebyer** [comment]
> @drivebyer Well after introducing the `qemu` the time for building the image has gone really up. to 2hrs previously it was 8min.
> 
> not a big deal right now. But probably in the future, this could be a fix. Right now it works well.

Sure, I will pay attention to this.

**Pull request merged**
