### PR TITLE
Fix PID file error in Docker containers

### PR DESCRIPTION
**Pull request by gazdagandras**
Using Openshift/OKD the docker containers complains about PID file error due to missing group permissions on /var/run folder.

### CODE REVIEW

**Comment by gazdagandras** [comment]
@shubham-cmyk Hi!

Thanks for merging my Pull Request above. I can see there is an updated :latest image at https://quay.io/repository/opstree/redis?tab=tags. Could you please build a new image tag with the updated source code? I suppose v7.0.13 tag could be the next version.

I can't use :latest tag in production and want to get rid of custom docker image.

Should I make another pull request for https://github.com/OT-CONTAINER-KIT/redis-operator?

**Comment by shubham-cmyk** [comment]
@gazdagandras The redis server was v7.2.3 
i have made the copy of the image now the tag should be available as `quay.io/opstree/redis:v7.2.3 `

**Comment by gazdagandras** [comment]
> @gazdagandras The redis server was v7.2.3 i have made the copy of the image now the tag should be available as `quay.io/opstree/redis:v7.2.3 `

Could you do this with the redis-sentinel image also? 

Thanks a lot!

**Comment by shubham-cmyk** [comment]
Done

**Pull request merged**
